### ISSUE TITLE
What should the next tagged release be?

### ISSUE THREAD

**Issue by ecaron** [stojg/crop#20]
I think it should be v1.3.0, because of the auto-orient functionality added since 1.2.10. Any objections?

**Comment by jdeniau** [comment]
:+1: as it is a new feature more than a bugfix

**Comment by stojg** [comment]
Yeah, sounds good, I like us to follow http://semver.org/

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
