### ISSUE TITLE
Imagecow implementation

### ISSUE THREAD

**Issue by oscarotero** [stojg/crop#23]
Hi. I'm the creator of [oscarotero/imagecow](https://github.com/oscarotero/imagecow), a simple library for basic image manipulations (resize, crop, rotate and not much more).
The library has a `crop()` and `resizeCrop` methods and I wanted to use this library to provide a way to use the Entropy and other methods. The best way to do it is include this library as a dependency (using composer) but all methods used for the calculations are protected so I had to copy/paste the code and do some changes [here's the result](https://github.com/oscarotero/imagecow/tree/master/src/Crops). According to the license, this is allowed (Redistribution and use in source and binary forms, with or without modification, are permitted...) and, of course, your copyright is included in Imagecow.

I just wanted to let you know about this and, if this library changes to a more reusable aproach, I will change Imagecow to include it as a dependency.

Thanks

**Comment by stojg** [comment]
Thank you,

If I ever find myself with an abundance of time and motivation I might spin the calculations out to so they can be reused. However I think that you made the right choice and copied the implementation so that you own it and can do whatever you feel like.
